import type { Constant } from './constants.d';

const constants: Constant = {
  AF: {
    icon: '🇦🇫',
    countryCode: 'AF',
    countryName: 'Afghanistan',
    callingCode: '93',
    regex: '^(\\+93|93)?[2-9]\\d{8}$',
  },
  AL: {
    icon: '🇦🇱',
    countryCode: 'AL',
    countryName: 'Albania',
    callingCode: '355',
    regex: '^(\\+355|355)?[67]\\d{8}$',
  },
  DZ: {
    icon: '🇩🇿',
    countryCode: 'DZ',
    countryName: 'Algeria',
    callingCode: '213',
    regex: '^(\\+213|213)?[5-7]\\d{8}$',
  },
  AD: {
    icon: '🇦🇩',
    countryCode: 'AD',
    countryName: 'Andorra',
    callingCode: '376',
    regex: '^(\\+376|376)?[3-9]\\d{5}$',
  },
  AO: {
    icon: '🇦🇴',
    countryCode: 'AO',
    countryName: 'Angola',
    callingCode: '244',
    regex: '^(\\+244|244)?9d{8}$',
  },
  AR: {
    icon: '🇦🇷',
    countryCode: 'AR',
    countryName: 'Argentina',
    callingCode: '54',
    regex: '^(\\+54|54)?[1-9]\\d{9}$',
  },
  AM: {
    icon: '🇦🇲',
    countryCode: 'AM',
    countryName: 'Armenia',
    callingCode: '374',
    regex: '^(\\+374|374)?[9]\\d{8}$',
  },
  AU: {
    icon: '🇦🇺',
    countryCode: 'AU',
    countryName: 'Australia',
    callingCode: '61',
    regex: '^(\\+61|61)?[2-9]\\d{8}$',
  },
  AT: {
    icon: '🇦🇹',
    countryCode: 'AT',
    countryName: 'Austria',
    callingCode: '43',
    regex: '^(\\+43|43)?[1-9]\\d{3,8}$',
  },
  AZ: {
    icon: '🇦🇿',
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    callingCode: '994',
    regex: '^(\\+994|994)?[50-59]\\d{7}$',
  },
  BH: {
    icon: '🇧🇭',
    countryCode: 'BH',
    countryName: 'Bahrain',
    callingCode: '973',
    regex: '^(\\+973|973)?[3-9]\\d{7}$',
  },
  BD: {
    icon: '🇧🇩',
    countryCode: 'BD',
    countryName: 'Bangladesh',
    callingCode: '880',
    regex: '^(\\+880|880)?1[3-9]\\d{8}$',
  },
  BY: {
    icon: '🇧🇾',
    countryCode: 'BY',
    countryName: 'Belarus',
    callingCode: '375',
    regex: '^(\\+375|375)?[2-9]\\d{7}$',
  },
  BE: {
    icon: '🇧🇪',
    countryCode: 'BE',
    countryName: 'Belgium',
    callingCode: '32',
    regex: '^(\\+32|32)?[1-9]\\d{7}$',
  },
  BJ: {
    icon: '🇧🇯',
    countryCode: 'BJ',
    countryName: 'Benin',
    callingCode: '229',
    regex: '^(\\+229|229)?[91-99]\\d{7}$',
  },
  BT: {
    icon: '🇧🇹',
    countryCode: 'BT',
    countryName: 'Bhutan',
    callingCode: '975',
    regex: '^(\\+975|975)?1d{7}$',
  },
  BO: {
    icon: '🇧🇴',
    countryCode: 'BO',
    countryName: 'Bolivia',
    callingCode: '591',
    regex: '^(\\+591|591)?[2-7]\\d{7}$',
  },
  BA: {
    icon: '🇧🇦',
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    callingCode: '387',
    regex: '^(\\+387|387)?6d{7}$',
  },
  BW: {
    icon: '🇧🇼',
    countryCode: 'BW',
    countryName: 'Botswana',
    callingCode: '267',
    regex: '^(\\+267|267)?7d{7}$',
  },
  BR: {
    icon: '🇧🇷',
    countryCode: 'BR',
    countryName: 'Brazil',
    callingCode: '55',
    regex: '^(\\+55|55)?[1-9]\\d{8}$',
  },
  BN: {
    icon: '🇧🇳',
    countryCode: 'BN',
    countryName: 'Brunei',
    callingCode: '673',
    regex: '^(\\+673|673)?[2-8]\\d{6}$',
  },
  BG: {
    icon: '🇧🇬',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    callingCode: '359',
    regex: '^(\\+359|359)?[8-9]\\d{8}$',
  },
  BF: {
    icon: '🇧🇫',
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    callingCode: '226',
    regex: '^(\\+226|226)?[70-79]\\d{6}$',
  },
  BI: {
    icon: '🇧🇮',
    countryCode: 'BI',
    countryName: 'Burundi',
    callingCode: '257',
    regex: '^(\\+257|257)?7d{7}$',
  },
  KH: {
    icon: '🇰🇭',
    countryCode: 'KH',
    countryName: 'Cambodia',
    callingCode: '855',
    regex: '^(\\+855|855)?[1-9]\\d{7}$',
  },
  CM: {
    icon: '🇨🇲',
    countryCode: 'CM',
    countryName: 'Cameroon',
    callingCode: '237',
    regex: '^(\\+237|237)?[2-7]\\d{7}$',
  },
  CA: {
    icon: '🇨🇦',
    countryCode: 'CA',
    countryName: 'Canada',
    callingCode: '1',
    regex: '^(\\+1|1)?[2-9]\\d{9}$',
  },
  CV: {
    icon: '🇨🇻',
    countryCode: 'CV',
    countryName: 'Cape Verde',
    callingCode: '238',
    regex: '^(\\+238|238)?[2-9]\\d{6}$',
  },
  KY: {
    icon: '🇰🇾',
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    callingCode: '1-345',
    regex: '^(\\+1-345|1-345)?[345]\\d{6}$',
  },
  CF: {
    icon: '🇨🇫',
    countryCode: 'CF',
    countryName: 'Central African Republic',
    callingCode: '236',
    regex: '^(\\+236|236)?[7-8]\\d{7}$',
  },
  TD: {
    icon: '🇹🇩',
    countryCode: 'TD',
    countryName: 'Chad',
    callingCode: '235',
    regex: '^(\\+235|235)?[7-9]\\d{7}$',
  },
  CL: {
    icon: '🇨🇱',
    countryCode: 'CL',
    countryName: 'Chile',
    callingCode: '56',
    regex: '^(\\+56|56)?[2-9]\\d{8}$',
  },
  CN: {
    icon: '🇨🇳',
    countryCode: 'CN',
    countryName: 'China',
    callingCode: '86',
    regex: '^(\\+86|86)?1[3-9]\\d{9}$',
  },
  CO: {
    icon: '🇨🇴',
    countryCode: 'CO',
    countryName: 'Colombia',
    callingCode: '57',
    regex: '^(\\+57|57)?[1-9]\\d{9}$',
  },
  KM: {
    icon: '🇰🇲',
    countryCode: 'KM',
    countryName: 'Comoros',
    callingCode: '269',
    regex: '^(\\+269|269)?3d{7}$',
  },
  CG: {
    icon: '🇨🇬',
    countryCode: 'CG',
    countryName: 'Congo',
    callingCode: '242',
    regex: '^(\\+242|242)?[7-9]\\d{7}$',
  },
  CD: {
    icon: '🇨🇩',
    countryCode: 'CD',
    countryName: 'Congo (Congo-Kinshasa)',
    callingCode: '243',
    regex: '^(\\+243|243)?[7-9]\\d{7}$',
  },
  CR: {
    icon: '🇨🇷',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    callingCode: '506',
    regex: '^(\\+506|506)?[2-8]\\d{6}$',
  },
  CI: {
    icon: '🇨🇮',
    countryCode: 'CI',
    countryName: "Côte \\d'Ivoire",
    callingCode: '225',
    regex: '^(\\+225|225)?[0-9]\\d{7}$',
  },
  HR: {
    icon: '🇭🇷',
    countryCode: 'HR',
    countryName: 'Croatia',
    callingCode: '385',
    regex: '^(\\+385|385)?[1-9]\\d{7}$',
  },
  CU: {
    icon: '🇨🇺',
    countryCode: 'CU',
    countryName: 'Cuba',
    callingCode: '53',
    regex: '^(\\+53|53)?[2-9]\\d{7}$',
  },
  CY: {
    icon: '🇨🇾',
    countryCode: 'CY',
    countryName: 'Cyprus',
    callingCode: '357',
    regex: '^(\\+357|357)?[2-9]\\d{6}$',
  },
  CZ: {
    icon: '🇨🇿',
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    callingCode: '420',
    regex: '^(\\+420|420)?[2-9]\\d{8}$',
  },
  DK: {
    icon: '🇩🇰',
    countryCode: 'DK',
    countryName: 'Denmark',
    callingCode: '45',
    regex: '^(\\+45|45)?[2-9]\\d{7}$',
  },
  DJ: {
    icon: '🇩🇯',
    countryCode: 'DJ',
    countryName: 'Djibouti',
    callingCode: '253',
    regex: '^(\\+253|253)?[2-9]\\d{6}$',
  },
  DM: {
    icon: '🇩🇲',
    countryCode: 'DM',
    countryName: 'Dominica',
    callingCode: '1767',
    regex: '^(\\+1767|1767)?[1-9]\\d{6}$',
  },
  DO: {
    icon: '🇩🇴',
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    callingCode: '1809',
    regex: '^(\\+1809|1809)?[1-9]\\d{7}$',
  },
  EC: {
    icon: '🇪🇨',
    countryCode: 'EC',
    countryName: 'Ecuador',
    callingCode: '593',
    regex: '^(\\+593|593)?[2-9]\\d{8}$',
  },
  EG: {
    icon: '🇪🇬',
    countryCode: 'EG',
    countryName: 'Egypt',
    callingCode: '20',
    regex: '^(\\+20|20)?[1-9]\\d{8}$',
  },
  SV: {
    icon: '🇸🇻',
    countryCode: 'SV',
    countryName: 'El Salvador',
    callingCode: '503',
    regex: '^(\\+503|503)?[2-9]\\d{7}$',
  },
  GQ: {
    icon: '🇬🇶',
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    callingCode: '240',
    regex: '^(\\+240|240)?[2-9]\\d{7}$',
  },
  ER: {
    icon: '🇪🇷',
    countryCode: 'ER',
    countryName: 'Eritrea',
    callingCode: '291',
    regex: '^(\\+291|291)?[2-9]\\d{6}$',
  },
  EE: {
    icon: '🇪🇪',
    countryCode: 'EE',
    countryName: 'Estonia',
    callingCode: '372',
    regex: '^(\\+372|372)?[2-9]\\d{7}$',
  },
  ET: {
    icon: '🇪🇹',
    countryCode: 'ET',
    countryName: 'Ethiopia',
    callingCode: '251',
    regex: '^(\\+251|251)?[1-9]\\d{8}$',
  },
  FJ: {
    icon: '🇫🇯',
    countryCode: 'FJ',
    countryName: 'Fiji',
    callingCode: '679',
    regex: '^(\\+679|679)?7d{5}$',
  },
  FI: {
    icon: '🇫🇮',
    countryCode: 'FI',
    countryName: 'Finland',
    callingCode: '358',
    regex: '^(\\+358|358)?[0-9]\\d{6,9}$',
  },
  FR: {
    icon: '🇫🇷',
    countryCode: 'FR',
    countryName: 'France',
    callingCode: '33',
    regex: '^(\\+33|33)?[1-9]\\d{8}$',
  },
  GA: {
    icon: '🇬🇦',
    countryCode: 'GA',
    countryName: 'Gabon',
    callingCode: '241',
    regex: '^(\\+241|241)?[2-9]\\d{6}$',
  },
  GM: {
    icon: '🇬🇲',
    countryCode: 'GM',
    countryName: 'Gambia',
    callingCode: '220',
    regex: '^(\\+220|220)?[3-9]\\d{6}$',
  },
  GE: {
    icon: '🇬🇪',
    countryCode: 'GE',
    countryName: 'Georgia',
    callingCode: '995',
    regex: '^(\\+995|995)?[3-9]\\d{8}$',
  },
  DE: {
    icon: '🇩🇪',
    countryCode: 'DE',
    countryName: 'Germany',
    callingCode: '49',
    regex: '^(\\+49|49)?[1-9]\\d{7,10}$',
  },
  GH: {
    icon: '🇬🇭',
    countryCode: 'GH',
    countryName: 'Ghana',
    callingCode: '233',
    regex: '^(\\+233|233)?[2-9]\\d{7}$',
  },
  GR: {
    icon: '🇬🇷',
    countryCode: 'GR',
    countryName: 'Greece',
    callingCode: '30',
    regex: '^(\\+30|30)?[1-9]\\d{8}$',
  },
  GD: {
    icon: '🇬🇩',
    countryCode: 'GD',
    countryName: 'Grenada',
    callingCode: '1-473',
    regex: '^(\\+1-473|1-473)?[1-9]\\d{6}$',
  },
  GU: {
    icon: '🇬🇺',
    countryCode: 'GU',
    countryName: 'Guam',
    callingCode: '1-671',
    regex: '^(\\+1-671|1-671)?[1-9]\\d{6}$',
  },
  GT: {
    icon: '🇬🇹',
    countryCode: 'GT',
    countryName: 'Guatemala',
    callingCode: '502',
    regex: '^(\\+502|502)?[2-9]\\d{7}$',
  },
  GN: {
    icon: '🇬🇳',
    countryCode: 'GN',
    countryName: 'Guinea',
    callingCode: '224',
    regex: '^(\\+224|224)?[2-9]\\d{7}$',
  },
  GW: {
    icon: '🇬🇼',
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    callingCode: '245',
    regex: '^(\\+245|245)?[2-9]\\d{7}$',
  },
  GY: {
    icon: '🇬🇾',
    countryCode: 'GY',
    countryName: 'Guyana',
    callingCode: '592',
    regex: '^(\\+592|592)?[2-9]\\d{7}$',
  },
  HT: {
    icon: '🇭🇹',
    countryCode: 'HT',
    countryName: 'Haiti',
    callingCode: '509',
    regex: '^(\\+509|509)?[2-9]\\d{7}$',
  },
  HN: {
    icon: '🇭🇳',
    countryCode: 'HN',
    countryName: 'Honduras',
    callingCode: '504',
    regex: '^(\\+504|504)?[2-9]\\d{7}$',
  },
  HU: {
    icon: '🇭🇺',
    countryCode: 'HU',
    countryName: 'Hungary',
    callingCode: '36',
    regex: '^(\\+36|36)?[1-9]\\d{7}$',
  },
  IS: {
    icon: '🇮🇸',
    countryCode: 'IS',
    countryName: 'Iceland',
    callingCode: '354',
    regex: '^(\\+354|354)?[1-9]\\d{6}$',
  },
  IN: {
    icon: '🇮🇳',
    countryCode: 'IN',
    countryName: 'India',
    callingCode: '91',
    regex: '^(\\+91|91)?[7-9]\\d{9}$',
  },
  ID: {
    icon: '🇮🇩',
    countryCode: 'ID',
    countryName: 'Indonesia',
    callingCode: '62',
    regex: '^(\\+62|62)?[1-9]\\d{8,9}$',
  },
  IR: {
    icon: '🇮🇷',
    countryCode: 'IR',
    countryName: 'Iran',
    callingCode: '98',
    regex: '^(\\+98|98)?[1-9]\\d{8}$',
  },
  IQ: {
    icon: '🇮🇶',
    countryCode: 'IQ',
    countryName: 'Iraq',
    callingCode: '964',
    regex: '^(\\+964|964)?[7-9]\\d{8}$',
  },
  IE: {
    icon: '🇮🇪',
    countryCode: 'IE',
    countryName: 'Ireland',
    callingCode: '353',
    regex: '^(\\+353|353)?[1-9]\\d{7}$',
  },
  IL: {
    icon: '🇮🇱',
    countryCode: 'IL',
    countryName: 'Israel',
    callingCode: '972',
    regex: '^(\\+972|972)?[2-9]\\d{7}$',
  },
  IT: {
    icon: '🇮🇹',
    countryCode: 'IT',
    countryName: 'Italy',
    callingCode: '39',
    regex: '^(\\+39|39)?[1-9]\\d{8}$',
  },
  JM: {
    icon: '🇯🇲',
    countryCode: 'JM',
    countryName: 'Jamaica',
    callingCode: '1876',
    regex: '^(\\+1876|1876)?[1-9]\\d{6}$',
  },
  JP: {
    icon: '🇯🇵',
    countryCode: 'JP',
    countryName: 'Japan',
    callingCode: '81',
    regex: '^(\\+81|81)?[1-9]\\d{8}$',
  },
  JO: {
    icon: '🇯🇴',
    countryCode: 'JO',
    countryName: 'Jordan',
    callingCode: '962',
    regex: '^(\\+962|962)?[7-9]\\d{8}$',
  },
  KZ: {
    icon: '🇰🇿',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    callingCode: '7',
    regex: '^(\\+7|7)?[1-9]\\d{9}$',
  },
  KE: {
    icon: '🇰🇪',
    countryCode: 'KE',
    countryName: 'Kenya',
    callingCode: '254',
    regex: '^(\\+254|254)?[7-9]\\d{8}$',
  },
  KI: {
    icon: '🇰🇮',
    countryCode: 'KI',
    countryName: 'Kiribati',
    callingCode: '686',
    regex: '^(\\+686|686)?[2-9]\\d{5}$',
  },
  KW: {
    icon: '🇰🇼',
    countryCode: 'KW',
    countryName: 'Kuwait',
    callingCode: '965',
    regex: '^(\\+965|965)?[2-9]\\d{6}$',
  },
  KG: {
    icon: '🇰🇬',
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    callingCode: '996',
    regex: '^(\\+996|996)?[7-9]\\d{8}$',
  },
  LA: {
    icon: '🇱🇸',
    countryCode: 'LA',
    countryName: 'Lesotho',
    callingCode: '266',
    regex: '^(\\+266|266)?[2-8]\\d{6}$',
  },
  LV: {
    icon: '🇱🇻',
    countryCode: 'LV',
    countryName: 'Latvia',
    callingCode: '371',
    regex: '^(\\+371|371)?[2-9]\\d{7}$',
  },
  LB: {
    icon: '🇱🇧',
    countryCode: 'LB',
    countryName: 'Lebanon',
    callingCode: '961',
    regex: '^(\\+961|961)?[1-9]\\d{7}$',
  },
  LS: {
    icon: '🇱🇸',
    countryCode: 'LS',
    countryName: 'Lesotho',
    callingCode: '266',
    regex: '^(\\+266|266)?[2-9]\\d{6}$',
  },
  LR: {
    icon: '🇱🇷',
    countryCode: 'LR',
    countryName: 'Liberia',
    callingCode: '231',
    regex: '^(\\+231|231)?[2-9]\\d{7}$',
  },
  LY: {
    icon: '🇱🇾',
    countryCode: 'LY',
    countryName: 'Libya',
    callingCode: '218',
    regex: '^(\\+218|218)?[2-9]\\d{7}$',
  },
  LI: {
    icon: '🇱🇮',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    callingCode: '423',
    regex: '^(\\+423|423)?[2-9]\\d{6}$',
  },
  LT: {
    icon: '🇱🇹',
    countryCode: 'LT',
    countryName: 'Lithuania',
    callingCode: '370',
    regex: '^(\\+370|370)?[6-9]\\d{7}$',
  },
  LU: {
    icon: '🇱🇺',
    countryCode: 'LU',
    countryName: 'Luxembourg',
    callingCode: '352',
    regex: '^(\\+352|352)?[2-9]\\d{6}$',
  },
  MO: {
    icon: '🇲🇴',
    countryCode: 'MO',
    countryName: 'Macau',
    callingCode: '853',
    regex: '^(\\+853|853)?[6-9]\\d{5}$',
  },
  MK: {
    icon: '🇲🇰',
    countryCode: 'MK',
    countryName: 'North Macedonia',
    callingCode: '389',
    regex: '^(\\+389|389)?[7-9]\\d{7}$',
  },
  MG: {
    icon: '🇲🇬',
    countryCode: 'MG',
    countryName: 'Madagascar',
    callingCode: '261',
    regex: '^(\\+261|261)?[3-9]\\d{7}$',
  },
  MW: {
    icon: '🇲🇼',
    countryCode: 'MW',
    countryName: 'Malawi',
    callingCode: '265',
    regex: '^(\\+265|265)?[2-9]\\d{7}$',
  },
  MY: {
    icon: '🇲🇾',
    countryCode: 'MY',
    countryName: 'Malaysia',
    callingCode: '60',
    regex: '^(\\+60|60)?[1-9]\\d{7}$',
  },
  MV: {
    icon: '🇲🇻',
    countryCode: 'MV',
    countryName: 'Maldives',
    callingCode: '960',
    regex: '^(\\+960|960)?[2-9]\\d{6}$',
  },
  ML: {
    icon: '🇲🇱',
    countryCode: 'ML',
    countryName: 'Mali',
    callingCode: '223',
    regex: '^(\\+223|223)?[6-9]\\d{7}$',
  },
  MT: {
    icon: '🇲🇹',
    countryCode: 'MT',
    countryName: 'Malta',
    callingCode: '356',
    regex: '^(\\+356|356)?[2-9]\\d{7}$',
  },
  MH: {
    icon: '🇲🇭',
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    callingCode: '692',
    regex: '^(\\+692|692)?[2-9]\\d{5}$',
  },
  MR: {
    icon: '🇲🇷',
    countryCode: 'MR',
    countryName: 'Mauritania',
    callingCode: '222',
    regex: '^(\\+222|222)?[2-9]\\d{7}$',
  },
  MU: {
    icon: '🇲🇺',
    countryCode: 'MU',
    countryName: 'Mauritius',
    callingCode: '230',
    regex: '^(\\+230|230)?[5-9]\\d{5}$',
  },
  YT: {
    icon: '🇾🇹',
    countryCode: 'YT',
    countryName: 'Mayotte',
    callingCode: '262',
    regex: '^(\\+262|262)?[2-9]\\d{6}$',
  },
  MX: {
    icon: '🇲🇽',
    countryCode: 'MX',
    countryName: 'Mexico',
    callingCode: '52',
    regex: '^(\\+52|52)?[1-9]\\d{9}$',
  },
  FM: {
    icon: '🇫🇲',
    countryCode: 'FM',
    countryName: 'Micronesia',
    callingCode: '691',
    regex: '^(\\+691|691)?[2-9]\\d{5}$',
  },
  MD: {
    icon: '🇲🇩',
    countryCode: 'MD',
    countryName: 'Moldova',
    callingCode: '373',
    regex: '^(\\+373|373)?[2-9]\\d{7}$',
  },
  MC: {
    icon: '🇲🇨',
    countryCode: 'MC',
    countryName: 'Monaco',
    callingCode: '377',
    regex: '^(\\+377|377)?[2-9]\\d{6}$',
  },
  MN: {
    icon: '🇲🇳',
    countryCode: 'MN',
    countryName: 'Mongolia',
    callingCode: '976',
    regex: '^(\\+976|976)?[1-9]\\d{7}$',
  },
  ME: {
    icon: '🇲🇪',
    countryCode: 'ME',
    countryName: 'Montenegro',
    callingCode: '382',
    regex: '^(\\+382|382)?[2-9]\\d{7}$',
  },
  MS: {
    icon: '🇲🇸',
    countryCode: 'MS',
    countryName: 'Montserrat',
    callingCode: '1-664',
    regex: '^(\\+1-664|1-664)?[1-9]\\d{6}$',
  },
  MA: {
    icon: '🇲🇦',
    countryCode: 'MA',
    countryName: 'Morocco',
    callingCode: '212',
    regex: '^(\\+212|212)?[6-7]\\d{8}$',
  },
  MZ: {
    icon: '🇲🇿',
    countryCode: 'MZ',
    countryName: 'Mozambique',
    callingCode: '258',
    regex: '^(\\+258|258)?[8-9]\\d{7}$',
  },
  MM: {
    icon: '🇲🇲',
    countryCode: 'MM',
    countryName: 'Myanmar',
    callingCode: '95',
    regex: '^(\\+95|95)?[9]\\d{7}$',
  },
  NA: {
    icon: '🇳🇦',
    countryCode: 'NA',
    countryName: 'Namibia',
    callingCode: '264',
    regex: '^(\\+264|264)?[1-9]\\d{7}$',
  },
  NR: {
    icon: '🇳🇷',
    countryCode: 'NR',
    countryName: 'Nauru',
    callingCode: '674',
    regex: '^(\\+674|674)?[2-9]\\d{5}$',
  },
  NP: {
    icon: '🇳🇵',
    countryCode: 'NP',
    countryName: 'Nepal',
    callingCode: '977',
    regex: '^(\\+977|977)?[1-9]\\d{8}$',
  },
  NL: {
    icon: '🇳🇱',
    countryCode: 'NL',
    countryName: 'Netherlands',
    callingCode: '31',
    regex: '^(\\+31|31)?[1-9]\\d{8}$',
  },
  NZ: {
    icon: '🇳🇿',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    callingCode: '64',
    regex: '^(\\+64|64)?[2-9]\\d{7}$',
  },
  NI: {
    icon: '🇳🇮',
    countryCode: 'NI',
    countryName: 'Nicaragua',
    callingCode: '505',
    regex: '^(\\+505|505)?[2-9]\\d{7}$',
  },
  NE: {
    icon: '🇳🇪',
    countryCode: 'NE',
    countryName: 'Niger',
    callingCode: '227',
    regex: '^(\\+227|227)?[7-9]\\d{7}$',
  },
  NG: {
    icon: '🇳🇬',
    countryCode: 'NG',
    countryName: 'Nigeria',
    callingCode: '234',
    regex: '^(\\+234|234)?[7-9]\\d{9}$',
  },
  KP: {
    icon: '🇰🇵',
    countryCode: 'KP',
    countryName: 'North Korea',
    callingCode: '850',
    regex: '^(\\+850|850)?[1-9]\\d{7}$',
  },
  NO: {
    icon: '🇳🇴',
    countryCode: 'NO',
    countryName: 'Norway',
    callingCode: '47',
    regex: '^(\\+47|47)?[2-9]\\d{7}$',
  },
  OM: {
    icon: '🇴🇲',
    countryCode: 'OM',
    countryName: 'Oman',
    callingCode: '968',
    regex: '^(\\+968|968)?[7-9]\\d{7}$',
  },
  PK: {
    icon: '🇵🇰',
    countryCode: 'PK',
    countryName: 'Pakistan',
    callingCode: '92',
    regex: '^(\\+92|92)?[3-9]\\d{9}$',
  },
  PA: {
    icon: '🇵🇦',
    countryCode: 'PA',
    countryName: 'Panama',
    callingCode: '507',
    regex: '^(\\+507|507)?[2-9]\\d{7}$',
  },
  PG: {
    icon: '🇵🇬',
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    callingCode: '675',
    regex: '^(\\+675|675)?[2-9]\\d{6}$',
  },
  PY: {
    icon: '🇵🇾',
    countryCode: 'PY',
    countryName: 'Paraguay',
    callingCode: '595',
    regex: '^(\\+595|595)?[1-9]\\d{7}$',
  },
  PE: {
    icon: '🇵🇪',
    countryCode: 'PE',
    countryName: 'Peru',
    callingCode: '51',
    regex: '^(\\+51|51)?[9]\\d{8}$',
  },
  PH: {
    icon: '🇵🇭',
    countryCode: 'PH',
    countryName: 'Philippines',
    callingCode: '63',
    regex: '^(\\+63|63)?[9]\\d{9}$',
  },
  PL: {
    icon: '🇵🇱',
    countryCode: 'PL',
    countryName: 'Poland',
    callingCode: '48',
    regex: '^(\\+48|48)?[1-9]\\d{8}$',
  },
  PT: {
    icon: '🇵🇹',
    countryCode: 'PT',
    countryName: 'Portugal',
    callingCode: '351',
    regex: '^(\\+351|351)?[2-9]\\d{8}$',
  },
  PR: {
    icon: '🇵🇷',
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    callingCode: '1787',
    regex: '^(\\+1787|1787)?[1-9]\\d{6}$',
  },
  QA: {
    icon: '🇶🇦',
    countryCode: 'QA',
    countryName: 'Qatar',
    callingCode: '974',
    regex: '^(\\+974|974)?[3-9]\\d{7}$',
  },
  RO: {
    icon: '🇷🇴',
    countryCode: 'RO',
    countryName: 'Romania',
    callingCode: '40',
    regex: '^(\\+40|40)?[1-9]\\d{8}$',
  },
  RU: {
    icon: '🇷🇺',
    countryCode: 'RU',
    countryName: 'Russia',
    callingCode: '7',
    regex: '^(\\+7|7)?[1-9]\\d{9}$',
  },
  RW: {
    icon: '🇷🇼',
    countryCode: 'RW',
    countryName: 'Rwanda',
    callingCode: '250',
    regex: '^(\\+250|250)?[7-9]\\d{8}$',
  },
  KN: {
    icon: '🇰🇳',
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    callingCode: '1869',
    regex: '^(\\+1869|1869)?[2-9]\\d{6}$',
  },
  SC: {
    icon: '🇸🇨',
    countryCode: 'SC',
    countryName: 'Seychelles',
    callingCode: '248',
    regex: '^(\\+248|248)?[2-9]\\d{6}$',
  },
  LC: {
    icon: '🇱🇨',
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    callingCode: '1758',
    regex: '^(\\+1758|1758)?[2-9]\\d{6}$',
  },
  SM: {
    icon: '🇸🇲',
    countryCode: 'SM',
    countryName: 'San Marino',
    callingCode: '378',
    regex: '^(\\+378|378)?[2-9]\\d{5}$',
  },
  ST: {
    icon: '🇸🇹',
    countryCode: 'ST',
    countryName: 'São Tomé and Príncipe',
    callingCode: '239',
    regex: '^(\\+239|239)?[2-9]\\d{6}$',
  },
  SA: {
    icon: '🇸🇦',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    callingCode: '966',
    regex: '^(\\+966|966)?[5-9]\\d{8}$',
  },
  SN: {
    icon: '🇸🇳',
    countryCode: 'SN',
    countryName: 'Senegal',
    callingCode: '221',
    regex: '^(\\+221|221)?[7-9]\\d{7}$',
  },
  RS: {
    icon: '🇷🇸',
    countryCode: 'RS',
    countryName: 'Serbia',
    callingCode: '381',
    regex: '^(\\+381|381)?[2-9]\\d{8}$',
  },
  SG: {
    icon: '🇸🇬',
    countryCode: 'SG',
    countryName: 'Singapore',
    callingCode: '65',
    regex: '^(\\+65|65)?[3-9]\\d{7}$',
  },
  SX: {
    icon: '🇸🇽',
    countryCode: 'SX',
    countryName: 'Sint Maarten',
    callingCode: '1721',
    regex: '^(\\+1721|1721)?[2-9]\\d{6}$',
  },
  SK: {
    icon: '🇸🇰',
    countryCode: 'SK',
    countryName: 'Slovakia',
    callingCode: '421',
    regex: '^(\\+421|421)?[2-9]\\d{8}$',
  },
  SI: {
    icon: '🇸🇮',
    countryCode: 'SI',
    countryName: 'Slovenia',
    callingCode: '386',
    regex: '^(\\+386|386)?[2-9]\\d{7}$',
  },
  SO: {
    icon: '🇸🇴',
    countryCode: 'SO',
    countryName: 'Somalia',
    callingCode: '252',
    regex: '^(\\+252|252)?[2-9]\\d{7}$',
  },
  ZA: {
    icon: '🇿🇦',
    countryCode: 'ZA',
    countryName: 'South Africa',
    callingCode: '27',
    regex: '^(\\+27|27)?[6-9]\\d{8}$',
  },
  KR: {
    icon: '🇰🇷',
    countryCode: 'KR',
    countryName: 'South Korea',
    callingCode: '82',
    regex: '^(\\+82|82)?[1-9]\\d{8}$',
  },
  SS: {
    icon: '🇸🇸',
    countryCode: 'SS',
    countryName: 'South Sudan',
    callingCode: '211',
    regex: '^(\\+211|211)?[1-9]\\d{8}$',
  },
  ES: {
    icon: '🇪🇸',
    countryCode: 'ES',
    countryName: 'Spain',
    callingCode: '34',
    regex: '^(\\+34|34)?[6-9]\\d{8}$',
  },
  LK: {
    icon: '🇱🇰',
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    callingCode: '94',
    regex: '^(\\+94|94)?[7-9]\\d{8}$',
  },
  SD: {
    icon: '🇸🇩',
    countryCode: 'SD',
    countryName: 'Sudan',
    callingCode: '249',
    regex: '^(\\+249|249)?[1-9]\\d{8}$',
  },
  SR: {
    icon: '🇸🇷',
    countryCode: 'SR',
    countryName: 'Suriname',
    callingCode: '597',
    regex: '^(\\+597|597)?[7-9]\\d{6}$',
  },
  SZ: {
    icon: '🇸🇿',
    countryCode: 'SZ',
    countryName: 'Eswatini',
    callingCode: '268',
    regex: '^(\\+268|268)?[2-9]\\d{6}$',
  },
  SE: {
    icon: '🇸🇪',
    countryCode: 'SE',
    countryName: 'Sweden',
    callingCode: '46',
    regex: '^(\\+46|46)?[2-9]\\d{7}$',
  },
  CH: {
    icon: '🇨🇭',
    countryCode: 'CH',
    countryName: 'Switzerland',
    callingCode: '41',
    regex: '^(\\+41|41)?[2-9]\\d{7}$',
  },
  SY: {
    icon: '🇸🇾',
    countryCode: 'SY',
    countryName: 'Syria',
    callingCode: '963',
    regex: '^(\\+963|963)?[1-9]\\d{8}$',
  },
  TJ: {
    icon: '🇹🇯',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    callingCode: '992',
    regex: '^(\\+992|992)?[9]\\d{8}$',
  },
  TZ: {
    icon: '🇹🇿',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    callingCode: '255',
    regex: '^(\\+255|255)?[7-9]\\d{8}$',
  },
  TH: {
    icon: '🇹🇭',
    countryCode: 'TH',
    countryName: 'Thailand',
    callingCode: '66',
    regex: '^(\\+66|66)?[8-9]\\d{8}$',
  },
  TG: {
    icon: '🇹🇬',
    countryCode: 'TG',
    countryName: 'Togo',
    callingCode: '228',
    regex: '^(\\+228|228)?[2-9]\\d{6}$',
  },
  TO: {
    icon: '🇹🇴',
    countryCode: 'TO',
    countryName: 'Tonga',
    callingCode: '676',
    regex: '^(\\+676|676)?[2-9]\\d{5}$',
  },
  TT: {
    icon: '🇹🇹',
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    callingCode: '1868',
    regex: '^(\\+1868|1868)?[2-9]\\d{6}$',
  },
  TN: {
    icon: '🇹🇳',
    countryCode: 'TN',
    countryName: 'Tunisia',
    callingCode: '216',
    regex: '^(\\+216|216)?[2-9]\\d{7}$',
  },
  TR: {
    icon: '🇹🇷',
    countryCode: 'TR',
    countryName: 'Turkey',
    callingCode: '90',
    regex: '^(\\+90|90)?[5-9]\\d{9}$',
  },
  TM: {
    icon: '🇹🇲',
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    callingCode: '993',
    regex: '^(\\+993|993)?[1-9]\\d{8}$',
  },
  TV: {
    icon: '🇹🇻',
    countryCode: 'TV',
    countryName: 'Tuvalu',
    callingCode: '688',
    regex: '^(\\+688|688)?[2-9]\\d{5}$',
  },
  UG: {
    icon: '🇺🇬',
    countryCode: 'UG',
    countryName: 'Uganda',
    callingCode: '256',
    regex: '^(\\+256|256)?[7-9]\\d{8}$',
  },
  UA: {
    icon: '🇺🇦',
    countryCode: 'UA',
    countryName: 'Ukraine',
    callingCode: '380',
    regex: '^(\\+380|380)?[1-9]\\d{8}$',
  },
  AE: {
    icon: '🇦🇪',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    callingCode: '971',
    regex: '^(\\+971|971)?[5-9]\\d{7}$',
  },
  GB: {
    icon: '🇬🇧',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    callingCode: '44',
    regex: '^(\\+44|44)?[1-9]\\d{8}$',
  },
  US: {
    icon: '🇺🇸',
    countryCode: 'US',
    countryName: 'United States',
    callingCode: '1',
    regex: '^(\\+1|1)?[2-9]\\d{9}$',
  },
  UY: {
    icon: '🇺🇾',
    countryCode: 'UY',
    countryName: 'Uruguay',
    callingCode: '598',
    regex: '^(\\+598|598)?[2-9]\\d{7}$',
  },
  UZ: {
    icon: '🇺🇿',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    callingCode: '998',
    regex: '^(\\+998|998)?[1-9]\\d{8}$',
  },
  VU: {
    icon: '🇻🇺',
    countryCode: 'VU',
    countryName: 'Vanuatu',
    callingCode: '678',
    regex: '^(\\+678|678)?[2-9]\\d{5}$',
  },
  VE: {
    icon: '🇻🇪',
    countryCode: 'VE',
    countryName: 'Venezuela',
    callingCode: '58',
    regex: '^(\\+58|58)?[4-9]\\d{8}$',
  },
  VN: {
    icon: '🇻🇳',
    countryCode: 'VN',
    countryName: 'Vietnam',
    callingCode: '84',
    regex: '^(\\+84|84)?[1-9]\\d{8}$',
  },
  WF: {
    icon: '🇼🇫',
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    callingCode: '681',
    regex: '^(\\+681|681)?[2-9]\\d{5}$',
  },
  YE: {
    icon: '🇾🇪',
    countryCode: 'YE',
    countryName: 'Yemen',
    callingCode: '967',
    regex: '^(\\+967|967)?[1-9]\\d{7}$',
  },
  ZM: {
    icon: '🇿🇲',
    countryCode: 'ZM',
    countryName: 'Zambia',
    callingCode: '260',
    regex: '^(\\+260|260)?[9]\\d{8}$',
  },
  ZW: {
    icon: '🇿🇼',
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    callingCode: '263',
    regex: '^(\\+263|263)?[7-9]\\d{8}$',
  },
};

export default constants;
